# Will handle selenium browser automation
# Before every action, we need to check if the browser is open
# and, in the case of multiple windows, which one is the one we want to use
# Each open window will be an instance of a custom class.
# Interacting with the browser will be done through this class.
import hashlib
import json
import os
import shutil
import traceback
import threading
import time
from urllib.parse import urlparse
from subprocess import CREATE_NO_WINDOW

import psutil
import win32con
import win32gui
from loguru import logger
from selenium.common.exceptions import WebDriverException
from selenium import webdriver
from selenium.webdriver.common.options import ArgOptions
from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
from selenium.webdriver.firefox.service import Service as FirefoxService
from selenium.webdriver.edge.service import Service as EdgeService
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.common.exceptions import NoSuchWindowException
import util

# Threads currently quitting replaced/hung drivers; joined at shutdown.
_PENDING_QUIT_THREADS = []

# When a browser can't start at all, every packet would otherwise trigger
# another launch attempt - each one flashing a window on screen and, every
# third try, a modal error box. Back off instead of retrying forever.
MAX_CONSECUTIVE_LAUNCH_FAILURES = 3
LAUNCH_FAILURE_COOLDOWN_SECONDS = 120

# Note: no CORS relaxation needed - umaserver sends Access-Control-Allow-Origin
# on every response, which is why Firefox (which has no CORS kill-switch for
# https pages) always worked.
FIREFOX_FORCED_PREFS = {
    # Firefox 150+ gates requests aimed at loopback/local addresses behind a
    # Local Network Access permission prompt ("<site> wants to access other apps
    # and services on this device", permission type loopback-network). The
    # helper page fetches our own server on 127.0.0.1, so it trips on every
    # fresh profile. 1 = ALLOW_ACTION, which makes the prompt auto-resolve.
    "permissions.default.loopback-network": 1,
}


def firefox_prefs_for(helper_url):
    """Forced prefs for a window pointed at `helper_url`.

    network.lna.skip-domains is checked twice against different hosts - once
    against the requesting site and once against the address being connected to
    - so both sides have to be listed for the Local Network Access check to be
    skipped outright.
    """
    prefs = dict(FIREFOX_FORCED_PREFS)
    helper_host = urlparse(helper_url).hostname
    domains = [d for d in (helper_host, "127.0.0.1", "localhost") if d]
    prefs["network.lna.skip-domains"] = ",".join(dict.fromkeys(domains))
    return prefs


def write_profile_user_js(profile_path, prefs):
    """Write `prefs` to user.js in a Firefox profile directory.

    user.js is the only file Firefox guarantees to read on every startup;
    prefs.js is owned by Firefox and rewritten when it exits. It also has to be
    rewritten on every launch rather than seeded once, because profiles created
    by older versions already exist on disk and would otherwise never pick up
    prefs added later.
    """
    lines = ["// Generated by Uma Launcher. Do not edit - rewritten on every launch.\n"]
    lines += [f"user_pref({json.dumps(key)}, {json.dumps(value)});\n"
              for key, value in prefs.items()]
    try:
        with open(os.path.join(profile_path, "user.js"), "w", encoding="utf-8") as f:
            f.writelines(lines)
    except OSError:
        # Not fatal: the prefs are also passed via Options below.
        logger.warning(f"Could not write user.js to {profile_path}:\n{traceback.format_exc()}")


def set_browser_version(options: ArgOptions, settings):
    if not settings['browser_version'] or not settings['browser_version'].strip():
        return
    options.browser_version = settings['browser_version']


def window_profile_dir(base_profile_path, url):
    """Per-window profile directory for `url`.

    A running browser instance holds an exclusive lock on its profile, and the
    helper and skills windows can run concurrently, so each window needs its own
    directory. Key on netloc+path only: the helper URL's query string encodes
    the deck and changes every career, and hashing it would spawn a fresh
    profile per run.
    """
    parsed_url = urlparse(url)
    url_slug = hashlib.md5(f"{parsed_url.netloc}{parsed_url.path}".encode("utf-8")).hexdigest()[:8]
    return f"{base_profile_path}_{url_slug}"

def firefox_setup(helper_url, settings):
    driver_path = None
    if settings['enable_browser_override']:
        new_path = settings['browser_custom_driver']
        if new_path:
            driver_path = new_path

    # Keep geckodriver's log out of the CWD (the install dir for the exe).
    firefox_service = FirefoxService(executable_path=driver_path,
                                     log_output=util.get_appdata("geckodriver.log"))
    firefox_service.creation_flags = CREATE_NO_WINDOW

    # Profile used IN PLACE via geckodriver's -profile argument. The
    # options.profile path clones the directory twice (copytree + base64-zip
    # extract), so Firefox only ever wrote to a throwaway copy and nothing -
    # cookies, site settings, "remember my choice" - survived a session. The
    # CLI argument is the one mechanism geckodriver documents as in-place.
    # Needs geckodriver >= 0.31.0 (Marionette port handling with custom
    # profiles); Selenium Manager fetches a current one automatically.
    base_profile = util.get_appdata("ff_profile")
    profile_dir = window_profile_dir(base_profile, helper_url)
    if not os.path.exists(profile_dir):
        # Seed from the legacy shared dir if present (keeps userChrome.css and
        # any manual tweaks), else from the bundled asset.
        seed = base_profile if os.path.exists(base_profile) else util.get_asset("ff_profile")
        shutil.copytree(seed, profile_dir)

    # Re-applied every launch so profiles created by older versions pick up
    # prefs added later; user_prefs the browser saves land in prefs.js and are
    # unaffected.
    forced_prefs = firefox_prefs_for(helper_url)
    write_profile_user_js(profile_dir, forced_prefs)

    options = webdriver.FirefoxOptions()
    set_browser_version(options, settings)
    options.add_argument("-profile")
    options.add_argument(profile_dir)
    # Also pass the forced prefs through Options: geckodriver applies these to
    # whatever profile it uses, so either path alone suffices and a change in
    # profile handling can't silently bring the prompt back.
    for pref_key, pref_value in forced_prefs.items():
        options.set_preference(pref_key, pref_value)

    binary_path = None

    if settings['enable_browser_override']:
        binary_path = settings['browser_custom_binary']
        if binary_path:
            options.binary_location = binary_path
    
    logger.debug(f"Firefox driver path: {driver_path}")
    logger.debug(f"Firefox binary path: {binary_path}")
    
    browser = webdriver.Firefox(service=firefox_service, options=options)
    _apply_firefox_adblock(browser, settings)
    browser.get(helper_url)
    return browser


UBLOCK_ADDON_ID = "uBlock0@raymondhill.net"


def _apply_firefox_adblock(browser, settings):
    """Install or remove the bundled uBlock Origin per the adblock setting.

    The profile is persistent and used in place, so an install survives
    restarts (installing again is a cheap upgrade/no-op) and disabling the
    setting has to actively uninstall. Never fatal: the helper works fine
    without it.
    """
    try:
        if settings['adblock_enabled']:
            xpi = util.get_asset("_assets/adblock/ublock_origin.xpi")
            if os.path.exists(xpi):
                browser.install_addon(xpi, temporary=False)
            else:
                logger.warning(f"Adblock enabled but bundled xpi missing: {xpi}")
        else:
            try:
                browser.uninstall_addon(UBLOCK_ADDON_ID)
            except WebDriverException:
                pass  # not installed - nothing to remove
    except Exception:
        logger.warning(f"Could not apply adblock setting:\n{traceback.format_exc()}")

def chromium_setup(service, options_class, driver_class, profile, helper_url, settings, binary_path=None):
    service.creation_flags = CREATE_NO_WINDOW
    options = options_class()
    set_browser_version(options, settings)

    if binary_path:
        options.binary_location = binary_path

    per_window_profile = window_profile_dir(profile, helper_url)

    options.add_argument(f"--user-data-dir={per_window_profile}")
    options.add_experimental_option("excludeSwitches", ["enable-automation"]) # Disable browser being controlled warning
    # No --disable-web-security: the only cross-origin traffic is helper page ->
    # umaserver, and umaserver sends CORS headers on every response. An
    # (elevated) browser session on a third-party site should not run with web
    # security disabled.
    # The launcher always runs elevated (util.elevate), and Chrome launched
    # elevated auto-de-elevates: it relaunches itself unelevated and the
    # original process exits, so chromedriver reports "Chrome instance exited"
    # while an orphaned, driverless window opens anyway. Every retry then
    # spawns another orphan. This switch tells Chrome to stay in the process
    # chromedriver spawned; it is a no-op when not elevated.
    options.add_argument("--do-not-de-elevate")

    if not settings['enable_browser_override']:
        options.add_argument("--app=" + helper_url)

    browser = driver_class(service=service, options=options)

    if settings['enable_browser_override']:
        browser.get(helper_url)

    logger.debug(f"Chromium started using profile {per_window_profile}")
    return browser

def chromium_service_kwargs(log_name, driver_path=None):
    """Service kwargs that capture why a Chromium browser failed to start.

    "Chrome instance exited" from the driver carries no reason; the driver's own
    verbose log has it (bad flag, profile lock, sandbox failure). Log to appdata
    the way geckodriver does, always verbose - it is a few KB per launch and it
    is the only record of a startup failure.
    """
    kwargs = {
        "log_output": util.get_appdata(log_name),
        "service_args": ["--verbose"],
    }
    if driver_path:
        kwargs["executable_path"] = driver_path
    return kwargs


def chrome_setup(helper_url, settings):
    driver_path = None
    if settings['enable_browser_override']:
        new_path = settings['browser_custom_driver']
        if new_path:
            driver_path = new_path

    binary_path = None
    if settings['enable_browser_override']:
        binary_path = settings['browser_custom_binary']

    logger.debug(f"Chrome driver path: {driver_path}")
    logger.debug(f"Chrome binary path: {binary_path}")

    return chromium_setup(
        service=ChromeService(**chromium_service_kwargs("chromedriver.log", driver_path)),
        options_class=webdriver.ChromeOptions,
        driver_class=webdriver.Chrome,
        profile=util.get_appdata("chr_profile"),
        helper_url=helper_url,
        settings=settings,
        binary_path=binary_path
    )

def edge_setup(helper_url, settings):
    return chromium_setup(
        service=EdgeService(**chromium_service_kwargs("edgedriver.log")),
        options_class=webdriver.EdgeOptions,
        driver_class=webdriver.Edge,
        profile=util.get_appdata("edg_profile"),
        helper_url=helper_url,
        settings=settings
    )

BROWSER_LIST = {
    'Firefox': firefox_setup,
    'Chrome': chrome_setup,
    'Edge': edge_setup,
}

def urls_match(url1, url2):
    """Whether two URLs point at the same page: netloc + path only.

    Query string and fragment are IGNORED on purpose. The helper URL's query
    encodes the deck (card/scenario/support ids) and changes every career, so
    exact matching would treat every new career as a different page and force
    a full reload instead of reusing the open tab.
    """
    url1 = url1[:-1] if url1.endswith('/') else url1
    url2 = url2[:-1] if url2.endswith('/') else url2
    urlparse1 = urlparse(url1)
    urlparse2 = urlparse(url2)
    return (urlparse1.netloc, urlparse1.path) == (urlparse2.netloc, urlparse2.path)


def ensure_focus(func):
    """Decorator for BrowserWindow methods that need a live, focused tab.

    Retries ensure_tab_open (which relaunches the browser if needed) up to 3
    times before running the wrapped method. If the browser still isn't up,
    reports the outage once - as a tray notification when the tray is
    available, falling back to the old modal warning box.
    """
    def wrapper(self, *args, **kwargs):
        with self._driver_lock:
            tries = 0

            while tries < 3:
                tries += 1
                self.ensure_tab_open()
                if self.driver:
                    return func(self, *args, **kwargs)

            # Report once per outage, not once per call - this runs off
            # packet handling, so it used to stack modal boxes forever.
            already_reported = self._reported_launch_failure
            self._reported_launch_failure = True

        if already_reported:
            return

        error_line = self.latest_error.strip() or "no error recorded"
        tray = getattr(self.threader, "tray", None)
        if tray and tray.notify(
                f"The helper browser could not be opened ({error_line}). "
                "Try selecting a different browser in the preferences.",
                "Uma Launcher: Unable to reach browser"):
            return
        # No tray (or toast failed): fall back to the modal box.
        util.show_warning_box("Uma Launcher: Unable to reach browser.", f"Webbrowser is unable to open.<br><br>If this problem persists, try restarting your computer<br>or selecting a different browser in the preferences.<br><br>Extra info:<br>{self.latest_error}")
    return wrapper


class BrowserWindow:
    def __init__(self, url, threader, rect=None, run_at_launch=None):
        self.url = url
        self.threader = threader
        self.settings = threader.settings
        self.driver: RemoteWebDriver = None
        self.active_tab_handle = None
        self.last_window_rect = {'x': rect[0], 'y': rect[1], 'width': rect[2], 'height': rect[3]} if rect else None
        self.run_at_launch = run_at_launch
        self.browser_name = "Auto"
        self.latest_error = ""
        # WebDriver sessions are not thread-safe, and this window is driven from
        # both the CarrotJuicer thread and the Flask (umaserver) thread. RLock
        # because locked methods call each other (ensure_focus -> ensure_tab_open).
        self._driver_lock = threading.RLock()
        self._consecutive_launch_failures = 0
        self._launch_blocked_until = 0.0
        self._reported_launch_failure = False

        self.ensure_tab_open()

    def init_browser(self) -> RemoteWebDriver:
        driver = None

        remaining_cooldown = self._launch_blocked_until - time.monotonic()
        if remaining_cooldown > 0:
            logger.debug(f"Browser launch backing off for another {remaining_cooldown:.0f}s")
            return None

        if self.settings['enable_browser_override']:
            selection = self.settings['custom_browser_type']
        else:
            selection = self.settings['selected_browser']
        browser_name = [
                    browser
                    for browser, selected in selection.items()
                    if selected
                ][0]
        self.browser_name = browser_name

        # Hack to convert override Chromium to Chrome
        if browser_name == 'Other (Chromium)':
            browser_name = 'Chrome'

        browser_list = []
        if browser_name == "Auto":
            browser_list = BROWSER_LIST.items()
        else:
            browser_list = [(browser_name, BROWSER_LIST[browser_name])]

        for browser_data in browser_list:
            browser_name, browser_setup = browser_data
            try:
                logger.info("Attempting " + str(browser_setup.__name__))
                driver = browser_setup(self.url, self.settings)
                self.browser_name = browser_name
                break
            except Exception as e:
                logger.error("Failed to start browser")
                logger.error(traceback.format_exc())
                self.latest_error = traceback.format_exception_only(type(e), e)[-1]
        if driver:
            self._consecutive_launch_failures = 0
            self._reported_launch_failure = False
        else:
            self._consecutive_launch_failures += 1
            if self._consecutive_launch_failures >= MAX_CONSECUTIVE_LAUNCH_FAILURES:
                self._launch_blocked_until = time.monotonic() + LAUNCH_FAILURE_COOLDOWN_SECONDS
                self._consecutive_launch_failures = 0
                logger.error(f"Browser failed to start {MAX_CONSECUTIVE_LAUNCH_FAILURES} times in a row; "
                             f"pausing launch attempts for {LAUNCH_FAILURE_COOLDOWN_SECONDS}s")

        if driver:
            # A hung page or script must raise instead of blocking the calling
            # thread forever (packet handling runs through this class).
            try:
                driver.set_page_load_timeout(30)
                driver.set_script_timeout(20)
            except WebDriverException:
                logger.warning(f"Could not set driver timeouts:\n{traceback.format_exc()}")
        return driver

    def alive(self):
        with self._driver_lock:
            if self.driver is None:
                return False
            try:
                return self.active_tab_handle in self.driver.window_handles
            except WebDriverException:
                return False

    def _reuse_existing_tab(self):
        """Try to keep using the current session. Returns True when the tab is
        usable and showing the right page; raises WebDriverException when the
        session is unusable and must be replaced."""
        if self.active_tab_handle not in self.driver.window_handles:
            raise WebDriverException("Active tab is gone")

        if self.driver.current_window_handle != self.active_tab_handle:
            if self.browser_name == 'Firefox':
                self.driver.switch_to.window(self.active_tab_handle)
            else:
                # App-mode Chrome/Edge can't reliably switch back; relaunch.
                raise WebDriverException("Active tab is no longer the current window")

        if urls_match(self.driver.current_url, self.url):
            if self.driver.execute_script("return window.from_script;"):
                self.last_window_rect = self.driver.get_window_rect()
                return True

        # Wrong page: navigate. get() blocks until the load finishes or the
        # page-load timeout raises - no marker-polling needed.
        self.driver.get(self.url)
        self.run_script_at_launch()
        return True

    def ensure_tab_open(self):
        with self._driver_lock:
            if self.driver:
                try:
                    if self._reuse_existing_tab():
                        return
                except WebDriverException:
                    logger.warning(f"Browser session unusable, replacing it:\n{traceback.format_exc()}")
                    # Quit off-thread: a dead session's quit() can block on the
                    # wire, and this path runs inside packet handling.
                    _quit_driver_async(self.driver)
                    self.driver = None

            self.driver = self.init_browser()

            try:
                if not self.driver or not self.driver.window_handles:
                    return
            except WebDriverException:
                logger.error("Failed to get window handles")
                logger.error(traceback.format_exc())
                return

            self.active_tab_handle = self.driver.window_handles[0]
            self.driver.switch_to.window(self.active_tab_handle)
            self.run_script_at_launch()
            self.last_window_rect = self.driver.get_window_rect()

    def run_script_at_launch(self):
        self.driver.execute_script("""window.from_script = true;""")
        if self.last_window_rect:
            self.driver.set_window_rect(self.last_window_rect['x'], self.last_window_rect['y'], self.last_window_rect['width'], self.last_window_rect['height'])
        if self.run_at_launch is not None:
            self.run_at_launch(self)

        # only want to do this for the training-event-helper
        if 'training-event-helper' in self.url:
            self.set_topmost(self.settings["browser_topmost"])

    def get_browser_pid(self):
        if self.driver is None:
            return None
        # Firefox reports its PID directly.
        if 'moz:processID' in self.driver.capabilities:
            return self.driver.capabilities['moz:processID']
        # Chromium: the browser is the driver service's direct child - no need
        # to scan the system process table.
        try:
            service_process = self.driver.service.process
            if service_process:
                children = psutil.Process(service_process.pid).children()
                if children:
                    return children[0].pid
        except (psutil.Error, AttributeError):
            logger.warning(f"Error getting browser PID from driver service:\n{traceback.format_exc()}")
        logger.warning("Could not get browser PID!")
        return None

    # TODO: It'd be nice to be able to do this without resorting to the win32 API
    def set_topmost(self, is_topmost):
        hwnd = util.get_window_handle_from_pid( self.get_browser_pid() )
        if hwnd is None:
            logger.error("Could not find window handle for browser PID.")
            return
        rect = util.get_window_rect(hwnd)
        # GetWindowRect returns (left, top, right, bottom), but we want (x, y, width, height)
        # TODO does this need flags?
        if is_topmost:
            logger.info( "Enabling always on top")
            win32gui.SetWindowPos(hwnd, win32con.HWND_TOPMOST, rect[0], rect[1], rect[2] - rect[0], rect[3] - rect[1], 0)
        else:
            logger.info( "Disabling always on top")
            win32gui.SetWindowPos(hwnd, win32con.HWND_NOTOPMOST, rect[0], rect[1], rect[2] - rect[0], rect[3] - rect[1], 0)
        self.settings["browser_topmost"] = is_topmost

    @ensure_focus
    def execute_script(self, *args, **kwargs):
        return self.driver.execute_script(*args, **kwargs)

    @ensure_focus
    def set_window_rect(self, rect):
        return self.driver.set_window_rect(*rect)
    
    @ensure_focus
    def get_window_rect(self):
        return self.driver.get_window_rect()

    def get_last_window_rect(self):
        return self.last_window_rect
    
    def current_url(self):
        return self.url

    def close(self):
        # Only close the active tab
        with self._driver_lock:
            try:
                if self.driver is not None and self.active_tab_handle in self.driver.window_handles:
                    self.driver.switch_to.window(self.active_tab_handle)
                    self.last_window_rect = self.driver.get_window_rect()
                    self.driver.close()
            except (NoSuchWindowException, WebDriverException):
                pass

    def quit(self):
        with self._driver_lock:
            self.close()
            _quit_driver_async(self.driver)
            self.driver = None


def quit_one_driver(driver):
    logger.debug(f"Closing driver in thread {threading.get_ident()}")
    if driver:
        try:
            driver.quit()
        except (NoSuchWindowException, WebDriverException):
            pass
    logger.debug(f"Finished closing driver in thread {threading.get_ident()}")

def _quit_driver_async(driver):
    """Quit a driver on a background thread, immediately.

    Replaced/hung sessions used to accumulate in a global list that was only
    drained at shutdown, leaving dead browser + driver processes running for
    the whole app session. Quitting can block on the wire, so it happens
    off-thread; threads are tracked so shutdown can join them.
    """
    if not driver:
        return
    quit_thread = threading.Thread(target=quit_one_driver, args=(driver,), daemon=True)
    _PENDING_QUIT_THREADS.append(quit_thread)
    quit_thread.start()

def quit_all_drivers():
    """Wait for any in-flight driver quits (bounded) at shutdown."""
    for quit_thread in _PENDING_QUIT_THREADS:
        quit_thread.join(timeout=10)
    _PENDING_QUIT_THREADS.clear()

# Chromium Webdriver is a poopyhead