# Will handle selenium browser automation
# Before every action, we need to check if the browser is open
# and, in the case of multiple windows, which one is the one we want to use
# Each open window will be an instance of a custom class.
# Interacting with the browser will be done through this class.
import hashlib
import json
import os
import traceback
import time
import threading
from urllib.parse import urlparse
from subprocess import CREATE_NO_WINDOW

import psutil
import win32con
import win32gui
from loguru import logger
from selenium.common.exceptions import WebDriverException
from selenium import webdriver
from selenium.webdriver.common.options import ArgOptions
from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
from selenium.webdriver.firefox.service import Service as FirefoxService
from selenium.webdriver.edge.service import Service as EdgeService
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.common.exceptions import NoSuchWindowException
import util

OLD_DRIVERS = []

# Prefs that kill the "<site> wants to open this application" external-protocol
# prompt. gametora occasionally triggers it and there is nothing we ever want
# launched from the helper window, so refuse the hand-off outright rather than
# asking. external-default is deliberately scheme-agnostic: we don't know which
# protocol the page will try, and per-scheme prefs would only cover known ones.
FIREFOX_FORCED_PREFS = {
    "security.fileuri.strict_origin_policy": False,  # Disable CORS protections
    "security.external_protocol_requires_permission": False,
    "network.protocol-handler.external-default": False,
    "network.protocol-handler.warn-external-default": False,
}


def write_profile_user_js(profile_path, prefs):
    """Write `prefs` to user.js in a Firefox profile directory.

    user.js is the only file Firefox guarantees to read on every startup;
    prefs.js is owned by Firefox and rewritten when it exits. It also has to be
    rewritten on every launch rather than seeded once, because profiles created
    by older versions already exist on disk and would otherwise never pick up
    prefs added later.
    """
    lines = ["// Generated by Uma Launcher. Do not edit - rewritten on every launch.\n"]
    lines += [f"user_pref({json.dumps(key)}, {json.dumps(value)});\n"
              for key, value in prefs.items()]
    try:
        with open(os.path.join(profile_path, "user.js"), "w", encoding="utf-8") as f:
            f.writelines(lines)
    except OSError:
        # Not fatal: the prefs are also passed via Options below.
        logger.warning(f"Could not write user.js to {profile_path}:\n{traceback.format_exc()}")


def set_browser_version(options: ArgOptions, settings):
    if not settings['browser_version'] or not settings['browser_version'].strip():
        return
    options.browser_version = settings['browser_version']

def firefox_setup(helper_url, settings):
    driver_path = None
    if settings['enable_browser_override']:
        new_path = settings['browser_custom_driver']
        if new_path:
            driver_path = new_path

    firefox_service = FirefoxService(executable_path=driver_path)
    firefox_service.creation_flags = CREATE_NO_WINDOW

    # Use a persistent profile in appdata so extensions/settings survive restarts.
    # Seed from the bundled ff_profile on first run.
    persistent_profile_path = util.get_appdata("ff_profile")
    if not os.path.exists(persistent_profile_path):
        import shutil
        shutil.copytree(util.get_asset("ff_profile"), persistent_profile_path)

    # Selenium clones this directory to a temp dir on every launch and Firefox
    # only ever touches the clone, so nothing the browser writes survives the
    # session - including the "Remember my choice" that would normally stop a
    # protocol prompt from reappearing. Baking the prefs into user.js first means
    # the clone carries them, and they are re-applied on every single start.
    write_profile_user_js(persistent_profile_path, FIREFOX_FORCED_PREFS)

    profile = webdriver.FirefoxProfile(persistent_profile_path)
    options = webdriver.FirefoxOptions()
    set_browser_version(options, settings)
    options.profile = profile
    # Also pass them through Options, which geckodriver applies independently of
    # the profile. Either path alone should be enough; both together means a
    # change in Selenium's profile handling can't silently bring the prompt back.
    for pref_key, pref_value in FIREFOX_FORCED_PREFS.items():
        options.set_preference(pref_key, pref_value)

    binary_path = None

    if settings['enable_browser_override']:
        binary_path = settings['browser_custom_binary']
        if binary_path:
            options.binary_location = binary_path
    
    logger.debug(f"Firefox driver path: {driver_path}")
    logger.debug(f"Firefox binary path: {binary_path}")
    
    browser = webdriver.Firefox(service=firefox_service, options=options)
    browser.get(helper_url)
    return browser

def chromium_setup(service, options_class, driver_class, profile, helper_url, settings, binary_path=None):
    service.creation_flags = CREATE_NO_WINDOW
    options = options_class()
    set_browser_version(options, settings)

    if binary_path:
        options.binary_location = binary_path

    # A user-data-dir can only be held by one running Chromium instance, and the
    # helper and skills windows are separate instances that may run at once, so
    # give each window its own dir keyed on its URL. Key on netloc+path only:
    # the helper URL's query string encodes the deck and changes every career,
    # and hashing it would spawn a fresh profile per run.
    parsed_url = urlparse(helper_url)
    url_slug = hashlib.md5(f"{parsed_url.netloc}{parsed_url.path}".encode("utf-8")).hexdigest()[:8]
    per_window_profile = f"{profile}_{url_slug}"

    options.add_argument(f"--user-data-dir={per_window_profile}")
    options.add_experimental_option("excludeSwitches", ["enable-automation"]) # Disable browser being controlled warning
    options.add_argument("--disable-web-security") # Disable CORS protections

    if not settings['enable_browser_override']:
        options.add_argument("--app=" + helper_url)

    browser = driver_class(service=service, options=options)

    if settings['enable_browser_override']:
        browser.get(helper_url)

    logger.debug(f"Chromium started using profile {per_window_profile}")
    return browser

def chrome_setup(helper_url, settings):
    driver_path = None
    if settings['enable_browser_override']:
        new_path = settings['browser_custom_driver']
        if new_path:
            driver_path = new_path
    
    binary_path = None
    if settings['enable_browser_override']:
        binary_path = settings['browser_custom_binary']

    logger.debug(f"Chrome driver path: {driver_path}")
    logger.debug(f"Chrome binary path: {binary_path}")

    return chromium_setup(
        service=ChromeService(executable_path=driver_path) if driver_path else ChromeService(),
        options_class=webdriver.ChromeOptions,
        driver_class=webdriver.Chrome,
        profile=util.get_appdata("chr_profile"),
        helper_url=helper_url,
        settings=settings,
        binary_path=binary_path
    )

def edge_setup(helper_url, settings):
    return chromium_setup(
        service=EdgeService(),
        options_class=webdriver.EdgeOptions,
        driver_class=webdriver.Edge,
        profile=util.get_appdata("edg_profile"),
        helper_url=helper_url,
        settings=settings
    )

BROWSER_LIST = {
    'Firefox': firefox_setup,
    'Chrome': chrome_setup,
    'Edge': edge_setup,
}

def urls_match(url1, url2):
    url1 = url1[:-1] if url1.endswith('/') else url1
    url2 = url2[:-1] if url2.endswith('/') else url2
    urlparse1 = urlparse(url1)
    urlparse2 = urlparse(url2)
    return (urlparse1.netloc, urlparse1.path) == (urlparse2.netloc, urlparse2.path)



class BrowserWindow:
    def __init__(self, url, threader, rect=None, run_at_launch=None):
        self.url = url
        self.threader = threader
        self.settings = threader.settings
        self.driver: RemoteWebDriver = None
        self.active_tab_handle = None
        self.last_window_rect = {'x': rect[0], 'y': rect[1], 'width': rect[2], 'height': rect[3]} if rect else None
        self.run_at_launch = run_at_launch
        self.browser_name = "Auto"
        self.latest_error = ""
        
        self.ensure_tab_open()

    def init_browser(self) -> RemoteWebDriver:
        driver = None

        if self.settings['enable_browser_override']:
            selection = self.settings['custom_browser_type']
        else:
            selection = self.settings['selected_browser']
        browser_name = [
                    browser
                    for browser, selected in selection.items()
                    if selected
                ][0]
        self.browser_name = browser_name

        # Hack to convert override Chromium to Chrome
        if browser_name == 'Other (Chromium)':
            browser_name = 'Chrome'

        browser_list = []
        if browser_name == "Auto":
            browser_list = BROWSER_LIST.items()
        else:
            browser_list = [(browser_name, BROWSER_LIST[browser_name])]

        for browser_data in browser_list:
            browser_name, browser_setup = browser_data
            try:
                logger.info("Attempting " + str(browser_setup.__name__))
                driver = browser_setup(self.url, self.settings)
                self.browser_name = browser_name
                break
            except Exception as e:
                logger.error("Failed to start browser")
                logger.error(traceback.format_exc())
                self.latest_error = traceback.format_exception_only(type(e), e)[-1]
        # if not driver:
        #     util.show_warning_box("Uma Launcher: Unable to start browser.", "Selected webbrowser cannot be started.")
        return driver

    def alive(self):
        if self.driver is None:
            return False
        try:
            if self.active_tab_handle in self.driver.window_handles:
                return True
        except:
            pass
        return False


    def ensure_tab_open(self):
        if self.driver:
            # Check if we have window handles
            try:
                window_handles = self.driver.window_handles
                try:
                    if self.active_tab_handle in window_handles:
                        if self.browser_name in ['Chrome', 'Edge']:
                            if self.driver.current_window_handle != self.active_tab_handle:
                                raise Exception("Wrong window handle")

                        if self.browser_name == 'Firefox' and self.driver.current_window_handle != self.active_tab_handle:
                            self.driver.switch_to.window(self.active_tab_handle)

                        if urls_match(self.driver.current_url, self.url):
                            from_script = self.driver.execute_script("return window.from_script;")
                            if from_script:
                                self.last_window_rect = self.driver.get_window_rect()
                                return
                        
                        self.driver.execute_script(f"document.still_the_old_page_haha = true;")  # Really reflects my mental state when I made this code
                        self.driver.execute_script(f"window.location = '{self.url}';")
                        # Wait for the page to load
                        while self.driver.execute_script("return document.still_the_old_page_haha;"):
                            time.sleep(0.2)
                        while self.driver.execute_script("return document.readyState;") != "complete":
                            time.sleep(0.2)
                        self.run_script_at_launch()
                        return
                except:
                    self.driver.quit()
                    self.driver = None
            except WebDriverException:
                pass
            OLD_DRIVERS.append(self.driver)

        self.driver = self.init_browser()

        try:
            if not self.driver or not self.driver.window_handles:
                return
        except WebDriverException as e:
            logger.error("Failed to get window handles")
            logger.error(traceback.format_exc())
            return

        self.active_tab_handle = self.driver.window_handles[0]
        self.driver.switch_to.window(self.active_tab_handle)
        self.run_script_at_launch()
        self.last_window_rect = self.driver.get_window_rect()

    def run_script_at_launch(self):
        self.driver.execute_script("""window.from_script = true;""")
        if self.last_window_rect:
            self.driver.set_window_rect(self.last_window_rect['x'], self.last_window_rect['y'], self.last_window_rect['width'], self.last_window_rect['height'])
        if self.run_at_launch is not None:
            self.run_at_launch(self)

        # only want to do this for the training-event-helper
        if 'training-event-helper' in self.url:
            self.set_topmost(self.settings["browser_topmost"])

    def ensure_focus(func):
        def wrapper(self, *args, **kwargs):
            tries = 0

            while tries < 3:
                tries += 1
                self.ensure_tab_open()
                if self.driver:
                    return func(self, *args, **kwargs)

            util.show_warning_box("Uma Launcher: Unable to reach browser.", f"Webbrowser is unable to open.<br><br>If this problem persists, try restarting your computer<br>or selecting a different browser in the preferences.<br><br>Extra info:<br>{self.latest_error}")
        return wrapper

    def get_browser_pid(self):
        if self.driver is not None and 'moz:processID' in self.driver.capabilities:
            return self.driver.capabilities['moz:processID']
        else:
            browsers = ['chrome.exe', 'msedge.exe', 'chromium.exe']
            if self.settings['enable_browser_override'] and self.settings['browser_custom_binary']:
                browsers.append( os.path.basename(self.settings['browser_custom_binary'])  )
            # Chromium-based (chrome/edge) browsers should be launched with the --app= flag.
            # The app flag isn't passed to custom browser binaries, so we check for that later
            for process in psutil.process_iter():
                try:
                    if process.name() in browsers:
                        if f'--app={self.url}' in process.cmdline():
                            return process.pid
                except Exception as e:
                    logger.warning( "Error getting browser PID:" )
                    logger.warning(traceback.format_exc())
            # If we didn't find a process with the --app= flag (likely a custom browser binary), try to find it by looking for the webdriver flag
            for process in psutil.process_iter():
                try:
                    if (process.name() in browsers
                        and '--test-type=webdriver' in process.cmdline()
                        and process.parent().name() not in browsers):
                        # Look for the top-level browser process only (it's what has the window)
                        return process.pid
                except Exception as e:
                    logger.warning( "Error getting browser PID:" )
                    logger.warning(traceback.format_exc())
            logger.warning("Could not get browser PID!")
            return None

    # TODO: It'd be nice to be able to do this without resorting to the win32 API
    def set_topmost(self, is_topmost):
        hwnd = util.get_window_handle_from_pid( self.get_browser_pid() )
        if hwnd is None:
            logger.error("Could not find window handle for browser PID.")
            return
        rect = util.get_window_rect(hwnd)
        # GetWindowRect returns (left, top, right, bottom), but we want (x, y, width, height)
        # TODO does this need flags?
        if is_topmost:
            logger.info( "Enabling always on top")
            win32gui.SetWindowPos(hwnd, win32con.HWND_TOPMOST, rect[0], rect[1], rect[2] - rect[0], rect[3] - rect[1], 0)
        else:
            logger.info( "Disabling always on top")
            win32gui.SetWindowPos(hwnd, win32con.HWND_NOTOPMOST, rect[0], rect[1], rect[2] - rect[0], rect[3] - rect[1], 0)
        self.settings["browser_topmost"] = is_topmost

    @ensure_focus
    def execute_script(self, *args, **kwargs):
        return self.driver.execute_script(*args, **kwargs)

    @ensure_focus
    def set_window_rect(self, rect):
        return self.driver.set_window_rect(*rect)
    
    @ensure_focus
    def get_window_rect(self):
        return self.driver.get_window_rect()

    def get_last_window_rect(self):
        return self.last_window_rect
    
    def current_url(self):
        return self.url

    def close(self):
        # Only close the active tab
        try:
            if self.driver is not None and self.active_tab_handle in self.driver.window_handles:
                self.driver.switch_to.window(self.active_tab_handle)
                self.last_window_rect = self.driver.get_window_rect()
                self.driver.close()
        except (NoSuchWindowException, WebDriverException):
            pass

    def quit(self):
        self.close()
        OLD_DRIVERS.append(self.driver)
        self.driver = None


def quit_one_driver(driver):
    logger.debug(f"Closing driver in thread {threading.get_ident()}")
    if driver:
        try:
            driver.quit()
        except (NoSuchWindowException, WebDriverException):
            pass
    logger.debug(f"Finished closing driver in thread {threading.get_ident()}")

def quit_all_drivers():
    global OLD_DRIVERS

    quit_threads = []
    for driver in OLD_DRIVERS:
        quit_threads.append(threading.Thread(target=quit_one_driver, args=(driver,)))

    for thread in quit_threads:
        thread.start()

    for thread in quit_threads:
        thread.join()

    OLD_DRIVERS = []

# Chromium Webdriver is a poopyhead